name: healthcare_webinar
description: ''
version: '0.1'
author: maciej+webinar-2022@prophecy.io
language: python
buildSystem: wheel
pipelines:
  pipelines/ingest_conditions:
    name: ingest_conditions
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-03-09 15:23:24'
    modifiedAt: '2023-03-09 15:25:21'
    datasets:
      inputs:
      - datasets/raw_conditions
      outputs:
      - datasets/bronze_conditions
    dependencies: {}
  pipelines/ingest_patients:
    name: ingest_patients
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-03-09 15:25:57'
    modifiedAt: '2023-03-09 15:27:51'
    datasets:
      inputs:
      - datasets/raw_patients
      outputs:
      - datasets/bronze_patients
    dependencies: {}
  pipelines/ingest_encounters:
    name: ingest_encounters
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-03-09 15:28:42'
    modifiedAt: '2023-03-09 15:29:57'
    datasets:
      inputs:
      - datasets/raw_encounters
      outputs:
      - datasets/bronze_encounters
    dependencies: {}
  pipelines/clean_conditions:
    name: clean_conditions
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-03-09 15:30:34'
    modifiedAt: '2023-03-09 15:31:58'
    datasets:
      inputs:
      - datasets/bronze_conditions
      outputs:
      - datasets/silver_conditions
    dependencies: {}
  pipelines/clean_patients:
    name: clean_patients
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-03-09 15:32:30'
    modifiedAt: '2023-03-09 15:33:36'
    datasets:
      inputs:
      - datasets/bronze_patients
      outputs:
      - datasets/silver_patients
    dependencies: {}
  pipelines/clean_encounters:
    name: clean_encounters
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-03-09 15:34:11'
    modifiedAt: '2023-03-09 17:09:14'
    datasets:
      inputs:
      - datasets/bronze_encounters
      outputs:
      - datasets/silver_encounters
    dependencies: {}
  pipelines/monthly_report:
    name: monthly_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    mode: batch
    language: python
    createdAt: '2023-03-09 17:45:31'
    modifiedAt: '2023-03-09 17:52:22'
    datasets:
      inputs:
      - datasets/patients_silver
      - datasets/silver_encounters
      outputs:
      - datasets/gold_report
    dependencies: {}
datasets:
  datasets/patients:
    name: patients
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 01:20:59'
    modifiedAt: '2023-03-09 01:20:59'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 01:20:59'
        modifiedAt: '2023-03-09 01:20:59'
  datasets/procedures:
    name: procedures
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 01:21:55'
    modifiedAt: '2023-03-09 01:22:18'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 01:21:55'
        modifiedAt: '2023-03-09 01:21:55'
  datasets/encounters:
    name: encounters
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 01:25:20'
    modifiedAt: '2023-03-09 01:25:20'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 01:25:20'
        modifiedAt: '2023-03-09 01:25:20'
  datasets/conditions:
    name: conditions
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 01:35:50'
    modifiedAt: '2023-03-09 01:35:50'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 01:35:50'
        modifiedAt: '2023-03-09 01:35:50'
  datasets/raw_conditions:
    name: raw_conditions
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 15:24:28'
    modifiedAt: '2023-03-09 15:24:28'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 15:24:28'
        modifiedAt: '2023-03-09 15:24:28'
  datasets/bronze_conditions:
    name: bronze_conditions
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 15:25:20'
    modifiedAt: '2023-03-09 15:25:20'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 15:25:20'
        modifiedAt: '2023-03-09 15:25:20'
  datasets/bronze_patients:
    name: bronze_patients
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 15:27:00'
    modifiedAt: '2023-03-09 15:27:44'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 15:27:00'
        modifiedAt: '2023-03-09 15:27:00'
  datasets/raw_patients:
    name: raw_patients
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 15:27:43'
    modifiedAt: '2023-03-09 15:27:43'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 15:27:43'
        modifiedAt: '2023-03-09 15:27:43'
  datasets/raw_encounters:
    name: raw_encounters
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 15:29:27'
    modifiedAt: '2023-03-09 15:29:27'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: File
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 15:29:27'
        modifiedAt: '2023-03-09 15:29:27'
  datasets/bronze_encounters:
    name: bronze_encounters
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 15:29:56'
    modifiedAt: '2023-03-09 15:29:56'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 15:29:56'
        modifiedAt: '2023-03-09 15:29:56'
  datasets/silver_conditions:
    name: silver_conditions
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 15:31:54'
    modifiedAt: '2023-03-09 15:31:54'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 15:31:54'
        modifiedAt: '2023-03-09 15:31:54'
  datasets/silver_patients:
    name: silver_patients
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 15:33:36'
    modifiedAt: '2023-03-09 15:33:36'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 15:33:36'
        modifiedAt: '2023-03-09 15:33:36'
  datasets/silver_encounters:
    name: silver_encounters
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 15:35:58'
    modifiedAt: '2023-03-09 15:36:52'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 15:35:58'
        modifiedAt: '2023-03-09 15:35:58'
  datasets/patients_silver:
    name: patients_silver
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 17:47:16'
    modifiedAt: '2023-03-09 17:47:16'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 17:47:16'
        modifiedAt: '2023-03-09 17:47:16'
  datasets/gold_report:
    name: gold_report
    description: ''
    author: maciej+webinar-2022@prophecy.io
    createdAt: '2023-03-09 17:52:21'
    modifiedAt: '2023-03-09 17:52:21'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1034
        datasetType: Database
        description: ''
        author: maciej+webinar-2022@prophecy.io
        createdAt: '2023-03-09 17:52:21'
        modifiedAt: '2023-03-09 17:52:21'
templates: {}
jobs:
  jobs/monthly_schedule:
    name: monthly_schedule
    description: ''
    fabricUID: 1034
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/ingest_conditions
    - pipelines/clean_conditions
    - pipelines/clean_encounters
    - pipelines/clean_patients
    - pipelines/ingest_patients
    - pipelines/monthly_report
    - pipelines/ingest_encounters
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-03-09 17:10:51'
    modifiedAt: '2023-03-09 17:52:57'
    author: maciej+webinar-2022@prophecy.io
libraries: []
subgraphs:
  subgraphs/cleanup_visits:
    name: cleanup_visits
    description: ''
    author: maciej+webinar-2022@prophecy.io
    language: python
    mode: batch
    createdAt: '2023-03-09 15:53:52'
    modifiedAt: '2023-03-09 17:51:32'
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
